### ISSUE TITLE
SRM only updates when closing game?

### ISSUE THREAD

**Issue by stephini** [Zarby89/ZeldaHud#1]
Hi, I know it's not an issue with your program but every emulator I have tried only updates the Save RAM when I close the emulator. Is there one you recommend that saves with some regularity making the HUD useful for streaming?

**Comment by Zarby89** [comment]
Hi, i recommend using Snes9x for the auto-update you can set the frequency of the save in the settings "Auto-Save S-RAM", i think it one of the only emulator that save while playing unfortunately, but it a great emulator and one of the most accurate
