### ISSUE TITLE
Auto-Updating Issues

### ISSUE THREAD

**Issue by BlueViper85** [Zarby89/ZeldaHud#2]
Hello!  I'm copying an issue from the Randomizer GitHub page here as there was mention of an issue with the HUD.  Below is the full text of the issue.  The last sentence being the issue relevant to the HUD.

I don't know their version, so you may need to contact him directly via the provided e-mail. But I wanted to make sure you saw it and could respond accordingly.  If it's fixed in the latest version, that's even better!

Thanks for all your efforts with this tool, Zarby!  It's incredibly useful :)

Paste:

Submitter: Tantalus-X
Email: Tantalus-X@hotmail.de
[v6]

the SRAM Trace make unlock switch option for all item the have 2 option Mushroom instantly to Magic Powder and Shovel to Flute + bird unlock instantly

me test Seed: C8302360

ps have you contact to Zarbry89 the hud rund not good and is bugy the hud add not Shields and the Flute item is Blue Mail in the Hud oO

**Comment by Zarby89** [comment]
Should be fixed in the new version
