### ISSUE TITLE
Bottles Take Multiple Clicks

### ISSUE THREAD

**Issue by BlueViper85** [Zarby89/ZeldaHud#3]
In the latest version of the HUD the bottles seem to take 2 clicks to get them to be filled with the first item.

So the flow goes something like this

Click once to change from inactive to active > click again to seemingly do nothing (is it skipping an item?) > Click again to fill with red potion

The same happens in reverse: right click to remove the potion > right click again to seemingly do nothing > right click once more to deactivate

**Comment by Zarby89** [comment]
They do take 2 click, it was mainly for the SRAM trace there is an "unexisting item" for some reason between the no bottle and the empty bottle i will remove it in the next version when you click Thanks.
0-No bottle 1-Mushroom 2-Empty bottle 3-Red Potion 4-Green Potion
5-Blue Potion 6-Fairy 7-Bee 8-Good Bee
