### ISSUE TITLE
Item Wrapping

### ISSUE THREAD

**Issue by BlueViper85** [Zarby89/ZeldaHud#4]
This may be intentional, but items with multiple click levels don't stop at their highest level.  This includes:
- Bottles
- Sword
- Shield
- Tunics

Sword, for example, goes like this

Inactive > Fighter Sword > Master Sword > Tempered Sword > Gold Sword > Fighter Sword

And the shield:

Inactive > Blue Shield > Fire Shield > Mirror Shield > Blue Shield

Only reporting because this is separate from the previous version, so if it's intentional I apologize and you can just close this.

Thanks, Zarby!

**Comment by Zarby89** [comment]
Thanks for the report, this is not intentional i made a new type of item "Heart Pieces" which are scrolling from empty to full and when the heart piece it full it go back empty but i forgot to limit it only to that item, so it will be fixed in the next version Thanks.
