### ISSUE TITLE
Weird Behaviour

### ISSUE THREAD

**Issue by Tsunami2069** [Zarby89/ZeldaHud#7]
Hello Zarby.

First of all, great work on this little tool. I've seen it being used on quite a lot of randomizer streamers.

However, im having an issue trying to get it to work myself.
Why? cause the tool seems to behave very odly.

First of all, when i try to edit the icons and change their positions or add / remove icons, things start to get weird. Moving icons / changing positions works fine but adding or removing icons is turning out to be a pain.
Whenever I try to remove an icon, a lot of the times it doesn't remove the icon or removes a completely different one. When i try to add, sometimes it doesn't add it.

Another weird behaviour is sometimes when i start the auto-updater, it makes a bunch of the icons just disappear.
Also the heart counter isn't working for me. But this is a minor issue, i planed on removing it anyways.

I have prepared a small video that demonstrates this (or at least the icon add / remove issue).
Here's the link: https://youtu.be/7a9EZCmSpJU
Don't worry, this video is not listed, so it won't be coming up on searches.

Can you help me out? Trying to get this to work so i could possibly use it on my stream.

Thanks, keep up the great work.

**Comment by miketrethewey** [comment]
In Edit Mode, when you right-click a spot on the HUD, it will modify whatever tracker is in that position.
If you choose "Remove" it'll remove the tracker in the spot that you opened the Add/Remove menu from.
If you choose "Add" it'll add/overwrite the tracker in the spot that you opened the Add/Remove menu from.

**Comment by Tsunami2069** [comment]
Oh that makes sense....
My bad, hehe, i totally thought that the remove button would remove whatever icon we had selected in the list of icons, not in the HUD itself...
Thank you @miketrethewey

**Comment by miketrethewey** [comment]
You're welcome!
We should keep this open so that Zarby can potentially speak to the issue about Auto-Updating as I haven't really experimented with that.

**Comment by Zarby89** [comment]
Hi, sorry for the late reply i didn't get any notification, the auto-update is not perfect and lots of items are not updated they'll just disapear, if you open the file itemlist.txt you'll see all the items that are auto-updated, all the items after "agahnim" are not auto-updated because the method used do not allow it unfortunately

**Comment by Tsunami2069** [comment]
Alright @Zarby89 Thanks for the reply...
At least now I know that it's just a limitation and not a real issue.

I think we can close this issue.

Keep up the great work.
