### ISSUE TITLE
Issues with Auto-Update

### ISSUE THREAD

**Issue by parciesca** [Zarby89/ZeldaHud#9]
This may somehow be associated to me but I'm seeing no guidance for this issue in any instructions or on the current or closed issues on your Git page here. I've had this problem since the first downloaded version of your HUD tool (HUDZelda.exe), and continues now that I've downloaded the newest version (zeldaGui.exe).

Anytime I set the auto-update on, it will black out most of the icons, select the flute, bomb, 3rd crystal, and 4th crystal as though I have obtained them, and never update. I'm using SNES9x, both 1.51 and latest version of 1.54.1. I've configured SNES9x to auto-save SRAM every second (was previously configured to every 30 seconds) and have both started a new save/new game/new SRM file and launched it before getting any items as well as loading it up for an existing SRM for a save that has multiple items. No matter what I do, it highlights those 4 items, blacks out most of them, and will not auto-update with items as I receive them. This is true whether I use a randomizer ROM from v5, v6, v7, the VT website's v8, or an original US ROM. This issue occurs regardless of  ROM, emulator, clean installs, different versions of the HUD.

**Comment by miketrethewey** [comment]
I'm just a volunteer here, but, I have heard this behavior manifest itself when the SRAM Trace flag is not in fact set in the specific instance of the ROM file that you're trying to extract using the SRAM Trace function.
The SRAM Trace flag actually enables the ability of the system to output the appropriate data to the appropriate memory addresses.

Please let me know if I have assumed incorrectly.

**Comment by parciesca** [comment]
Are you saying the ROM itself has to be flagged somehow? Or an option in the emulator? I currently prefer aLttP Randomizer v7, which has the ROM built in so if there's a way somehow to set a trace flag on the file after generating the seed, I've seen no guidance for it online.

**Comment by parciesca** [comment]
I see that option in the v7 software and VT page. I will see what I can do when I get home from work to enable that, but I did not previously observe that setting.

**Comment by miketrethewey** [comment]
On the VT site, the flag is not in an overt location. Recently, the spiffy pulsing effect was added for the ROM Options area.
That should be what you're missing.
I hope that gets you in the correct direction!

**Comment by parciesca** [comment]
That did it, my bad and thanks for the assist!
